##This illustrates the pipeline for generating data, fitting models, and detecting DMRs
##First source both the "RRBSsimulation.R" and "RRBSmodeling.R" scripts and make sure that all required libraries are installed 

##This specifies a set of profiles containing 500 sites with 8 samples (4 controls, 4 cases) with 10% of the sites differentially methylated in DMRs
##of length 250 with a PM difference of 50%
sim.n4.d50.l250=sim.bed.vg(nsites=500,nsamp=8,dm.len=250,prop.diff=0.10,pm.diff=0.50)

##View the first fow rows of simulated data.  "dmsites" in an indicator taking values (-1,0,1), "mprob" is the PM for group 1, "mprob.diff" 
##is the PM for group 2.  The next 8 columns contain the scores and the final 8 contain the PM values, with 1-4 corresponding to group 1 and 5-8
##corresponding to group 2. 
head(sim.n4.d50.l250[[1]])


##View the DMRs.  Column 1 contains the row indices for the DMR starts, column 2 contains the chrpos values, and column 3 contains the
##number of sites
head(sim.n4.d50.l250[[2]])

##Now fit models using the "fitmods.sim" function.  Specify the simulation matrix, the overall sample size, and a binary grouping vector of length nsamp.
##There may be some warning messages generated by the GLM function if PM levels are all 0% or 100% in a given group.  
mods.n4.d50.l250=fitmods.sim(x=sim.n4.d50.l250[[1]],nsamp=8,group.ind=c(0,0,0,0,1,1,1,1))

##If desired, the QUASASS adjustment can be performed at this point.  This can be time-consuming for large numbers of sites, but should take fewer than 5 minutes for this
##example.  The command is currently commented out for those who wish to run through this quickly.
##mods.n4.d50.l250=SSQA(mods.n4.d50.l250)

##Using either raw p-values, use the UP algorithm to identify DMRs:
dmrs.n4.d50.l250.r=dmrID(mods.n4.d50.l250,ptype="orig")
##Option for using adjusted values:
##dmrs.n4.d50.l250.q=dmrID(mods.n4.d50.l250,ptype="adj")

##View results.  Table provides the start and end positions for each DMR, number of sites, indicator of any missing sites, the DMR direction (group2-group1), 
##the average PMD, the log p-value associated with the DMR, and the row indices for the start and end positions.
dmrs.n4.d50.l250.r




